experiment:
  name: test_FINB_shot5
  cuda: [0]
dataset:
  name: CUB
  root_dir: ../datasets/CUB
  meta_dir: metadata/cub
  num_workers: 12
  way: 5                                                  # Number of categories per meta task
  shot: 5                                             # Number of samples per category
  query_shot: 16                                          # Number of samples per category for test
  trail: 1000
  transformer:
    resize_size: 184
    image_size: 160
sourcedataset:
  name: miniImageNet                                                                 # Here we use miniImageNet  dataset.
  root_dir: ../datasets/mini-ImageNet/images                                         # Path to the folder of images in miniImageNet.
  meta_dir: metadata/mini-ImageNet                                                   # Path to meta-data file for miniImageNet.
  num_workers: 12                                                                     # Number of workers for dataloader.
  way: 5                                                  # Number of categories per meta task
  shot: 1                                             # Number of samples per category
  query_shot: 16                                          # Number of samples per category for test
  trail: 1000
  transformer:
    image_size: 160                                                                  # The size of input image (160x160).
    resize_size: 184
model:
  name: FINB
  finetuning: FINBFinetuning                              # Consistent with model name
  is_pretraining: False
  use_transform: True
  num_classes: 5                                          # Number of categories per meta task
  resolution: 25
  load: results/res10/FINB/best_model.pth
finetuning:
  epoch: 50
  m_inter: 0.998
  m_target: 0.998
